#!/usr/bin/env ruby

option = ARGV[0]
filename = ARGV[1]

# Opcion en la que nos dice si el paquete está instalado o no
def check(f_package)
  status = `whereis #{f_package[0]} |grep bin |wc -l`.to_i
    if status == 0
      puts "#{f_package[0]} ->  (U) uninstalled"
    elsif status == 1
      puts "#{f_package[0]} ->  (I) installed"
    end

end
# Opción en la que si el paquete esta instalado se desinstalará y en el caso de que no este isntalado se instalará
def install(f_package)
  status = `whereis #{f_package[0]} |grep bin |wc -l`.to_i
  action = "#{f_package[1]}".to_s

  if action == "install"
    if status == 0
      `apt-get install -y #{f_package[0]}`
      puts "#{f_package[0]} -> (I) installed"
    elsif status == 1
      puts "#{f_package[0]} -> (I) ya está instalado"
    end

  elsif action == "remove"
      if status == 1
        `apt-get remove -y  #{f_package[0]}`
        puts "#{f_package[0]} -> (U) uninstalled"
      elsif status == 0
        puts "#{f_package[0]} -> (U) no está instalado"
      end
  end
end

# Opcion en la que se usa el parametro help

if option == '--help'
  puts 'Usage:
        systemctml [OPTIONS] [FILENAME]
Options:
        --help, mostrar esta ayuda.
        --version, mostrar información sobre el autor del script
                   y fecha de creación.
        --status FILENAME, comprueba si puede instalar/desintalar.
        --run FILENAME, instala/desinstala el software indicado.
Description:
        Este script se encarga de instalar/desinstalar
        el software indicado en el fichero FILENAME.
        Ejemplo de FILENAME:
        tree:install
        nmap:install
        atomix:remove'
# Opcion del comando con el parametro de version

elsif option == '--version'
  puts 'Autor: Pablo Rodríguez de la Sierra García
Fecha: 26/02/2021'

# Opcion del comando con el parametro de status

elsif option == '--status'
  file = `cat #{filename}`
  f_lines = file.split("\n")
  f_lines.each do |a|
    f_package = a.split(":")
    check(f_package)
  end

# Opción del comando sin ningún parámetro

elsif option.nil?
  puts 'Se aconseja el uso de "--help" para ver la ayuda.'

# Opcion del comando con el parametro de run impidiendo ejecutarlo sin ser root

elsif option == '--run'
  user = `id -u`.to_i

  if user == 0
    file = `cat #{filename}`
    f_lines = file.split("\n")
    f_lines.each do |a|
      f_package = a.split(":")
      install(f_package)
    end

  elsif user != 0
    puts "Se necesita ser usuario root para ejecutar el script"
    exit 1
  end
end
